# Generated by Django 4.2.7 on 2026-04-18 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(max_length=30, unique=True)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_address', models.TextField()),
                ('origin_city', models.CharField(choices=[('Jakarta', 'Jakarta'), ('Surabaya', 'Surabaya'), ('Bandung', 'Bandung'), ('Medan', 'Medan'), ('Semarang', 'Semarang'), ('Makassar', 'Makassar'), ('Bali', 'Bali'), ('Yogyakarta', 'Yogyakarta')], max_length=100)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_address', models.TextField()),
                ('destination_city', models.CharField(choices=[('Jakarta', 'Jakarta'), ('Surabaya', 'Surabaya'), ('Bandung', 'Bandung'), ('Medan', 'Medan'), ('Semarang', 'Semarang'), ('Makassar', 'Makassar'), ('Bali', 'Bali'), ('Yogyakarta', 'Yogyakarta')], max_length=100)),
                ('service_type', models.CharField(choices=[('REG', 'Regular (3-5 hari)'), ('EXP', 'Express (1-2 hari)'), ('SDS', 'Same Day'), ('CAR', 'Cargo')], default='REG', max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('package_description', models.TextField(blank=True)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ppn_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Picked Up'), ('TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('input_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
