# Generated by Django 4.2.7 on 2026-05-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='destination_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin_city',
            field=models.CharField(max_length=100),
        ),
    ]
